server:
  port: 9100
spring:
  application:
    name: user-outh
  redis:
    host: 192.168.64.128
    port: 16379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dongyimaidb?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 1234
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
outh:
  ttl: 3600  #token存储到redis的过期时间
  clientId: dongyimai
  clientSecret: dongyimai #密钥
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/dongyimai.jks  #证书位置
    secret: dongyimai  #密钥的访问密码
    alias: dongyimai   #密钥的别名
    password: dongyimai #密钥库的访问密码
