spring:
  application:
    name: gateway-web
#网关配置跨域请求问题：这里指的是允许你通过我的网关，并不代表其他服务
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有请求
            allowedOrigins: "*" #跨域处理允许所有的域
            allowedMethods: #支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      #网关路由规则
      routes:
        - id: dongyimai_goods_route
          uri: lb://DYM-SELLERGOODS
          predicates:
            - Path=/api/album/**,/api/brand**,/api/cache/**,/api/categoryBrand/**,/api/category/**,/api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**
          filters:
            - StripPrefix=1
        - id: dongyimai_user_route
          uri: lb://USER
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
            - StripPrefix=1
        #订单微服务
        - id: dongyimai_order_route
          uri: lb://order
          predicates:
            - Path=/api/cart/**,/api/categoryReport/**,/api/orderConfig/**,/api/order/**,/api/orderItem/**,/api/orderLog/**,/api/preferential/**,/api/returnCause/**,/api/returnOrder/**,/api/returnOrderItem/**
          filters:
            - StripPrefix=1
        #支付微服务
        - id: dongyimai_pay_route
          uri: lb://pay
          predicates:
            - Path=/api/pay/**
          filters:
            - StripPrefix=1
      #路由过滤原则
  #      routes:
#        - id: dongyimai_goods_route #可以随便起名
##         1,2,3 uri: http://localhost:9001
#          uri: lb://DYM-SELLERGOODS
#          predicates:
##          1.  - Host=cloud.guihaole.com**
##          2.  - Path=/item**
##          3.  - Path=/brand**
#            - Path=/api/brand**
#          filters:
#            #相当于给Path前面加上/brand===>访问localhost:8001  变成了 localhost:8001/brand
##           3. - PrefixPath=/api
##           3. - StripPrefix=1
#            - StripPrefix=1
##            - name: RequestRateLimiter  #请求数限流，名字不能随便写，使用默认的facatory
##              args:
##                key-resolver: "#{@ipKeyResolver}"
##                redis-rate-limiter.replenishRate: 1  #每秒1次
##                redis-rate-limiter.burstCapacity: 1  #最多多少个请求
  redis:
    host: 192.168.64.128
    port: 16379
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#开启网关服务
management:
  endpoint:
    gateway:
      enabled: true
  web:
    exposure:
      include: true

