server:
  port: 9001
spring:
  thymeleaf:
    prefix: classpath:/templates/   #在构建URL时预先查看名称的前缀
    suffix: .html   #构建URL时附加到查看名称的后缀
    cache: false
  application:
    name: UserWeb
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
